### PR TITLE
Merge `lib.py` changes to main

### PR DESCRIPTION
**Pull request by GrapesGoober**
# Changes
- New and reworked `lib` classes: `Sprite`, `GameObject`, `World`
- Updated pong example with new `lib` classes
- New worldfile format
- New docstring
- Updated readme.md

# Once Merged
- Delete this branch

### CODE REVIEW

**Comment by Tee55** [comment]
Why are there changes in assets/pong ?

**Comment by GrapesGoober** [comment]
@Tee55
- Pong is example code from my assignment
- I used the older version of `lib.py` to build pong
- I rewrote the `lib.py` classes, so there are changes to `pong` as well to reflect those changes

Just wanna clear up: this commit is me refactoring `lib.py` to be easier to use. As such, I need to rewrite some of pong as well, just function signatures and imports, to reflect those changes.

**Comment by GrapesGoober** [comment]
@Tee55 

Just FYI: the starting point for reading the diff should be
- `main.py`
- `lib.py`
- then dance around `assets/pong` to see how `lib.py` is being used with game logic

**Comment by Tee55** [comment]
I think the assets/pong should be rename to example/pong or other name because I always confuse with my normal workflow as assets folder is where I place my image texture, sound and other stuff.

**Review by Tee55 — APPROVED** [review]

**Comment by GrapesGoober** [comment]
@Tee55 

That is a good point. I think it's worth opening an issue.

The problem is that `World` class is coded to look into assets file. I didn't write any flexibility into the dynamic imports. This is a good point that I think should open a new issue to write flexibility into the imports. Maybe a new feature branch.

I got questions about file structure, but I'll leave that for the new issue

**Pull request merged**
